import { Nunito_Sans, Rubik } from 'next/font/google'
import "./globals.css";
import Header from '@/components/layout/Header/Header';
import TopAlert from '@/components/layout/Header/TopAlert';

const nunito_Sans = Nunito_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
const rubik = Rubik({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunito_Sans.className} ${rubik.className} antialiased`}
      >
      <TopAlert />
      <Header />
        {children}
      </body>
    </html>
  );
}
